// Code generated by protoc-gen-kratos-dart-http. DO NOT EDIT.

import 'package:json_annotation/json_annotation.dart';

part 'greeter.g.dart';

/// HelloRequest 类型定义了打招呼参数类型
@JsonSerializable()
class HelloRequest {
  const HelloRequest({
    required this.name,
  });

  /// 用户名
  final String name;

  factory HelloRequest.fromJson(Map<String, dynamic> json) {
    return _$HelloRequestFromJson(json);
  }

  Map<String, dynamic> toJson() => _$HelloRequestToJson(this);
}

/// HelloReply 类型是打招呼的返回信息类型
@JsonSerializable()
class HelloReply {
  const HelloReply({
    required this.message,
  });

  /// 响应信息
  final String message;

  factory HelloReply.fromJson(Map<String, dynamic> json) {
    return _$HelloReplyFromJson(json);
  }

  Map<String, dynamic> toJson() => _$HelloReplyToJson(this);
}
