// Code generated by protoc-gen-kratos-dart-http. DO NOT EDIT.

import 'dart:convert';
import 'package:kratos_plugin/kratos_plugin.dart';
import 'package:http/http.dart' as http;
import 'greeter.dart';

/// The greeting service definition.
abstract class GreeterClient {
  /// Sends a greeting
  Future<HelloReply> sayHello(HelloRequest request);
}

class GreeterClientImpl implements GreeterClient {
  final http.Client _client;

  const GreeterClientImpl(this._client);

  /// Sends a greeting
  @override
  Future<HelloReply> sayHello(HelloRequest req) async {
    final arg = RequestArg.fromPattern(
      const HttpRule(
        kind: "get",
        path: "/helloworld/{name}",
        body: "",
      ),
      req.toJson(),
    );

    final resp = await _client.get(arg.url, headers: {
      'Content-Type': 'application/json',
    });

    if (resp.statusCode >= 200 && resp.statusCode <= 299) {
      return HelloReply.fromJson(jsonDecode(resp.body));
    }
    throw KratosError.fromJson(jsonDecode(resp.body));
  }
}
