// Code generated by protoc-gen-kratos-dart-http. DO NOT EDIT.

import 'package:json_annotation/json_annotation.dart';

part 'greeter.g.dart';

/// The request message containing the user's name.
@JsonSerializable()
class HelloRequest {
  const HelloRequest({
    required this.name,
  });

  final String name;

  factory HelloRequest.fromJson(Map<String, dynamic> json) {
    return _$HelloRequestFromJson(json);
  }

  Map<String, dynamic> toJson() => _$HelloRequestToJson(this);
}

/// The response message containing the greetings
@JsonSerializable()
class HelloReply {
  const HelloReply({
    required this.message,
  });

  final String message;

  factory HelloReply.fromJson(Map<String, dynamic> json) {
    return _$HelloReplyFromJson(json);
  }

  Map<String, dynamic> toJson() => _$HelloReplyToJson(this);
}
